services:
  java-dev:
    build:
      context: .
      args:
        - USER=${USER:-user} # Your User Name
        - USER_ID=${USER_ID:-1000} # Your User ID
        - GROUP_ID=${GROUP_ID:-1000} # Your GROUP ID
        - JDK_VERSION=17 # Install Java Version
    image: java-dev:alpine
    container_name: java-dev
    volumes:
      - type: bind
        source: ./
        target: /WORKDIR
    tty: true
    command: sh
